export { default as Logo } from "./logo.png";
export { default as Android } from "./Rectangle 131.png";
export { default as Ios } from "./Rectangle 130.png";
export { default as Illustration } from "./iluss.png";
export { default as IllusCard } from "./smalpp-card.png";
export { default as Airpods } from "./airpods.png";
export { default as Iphone } from "./iphone.png";
export { default as Laptop } from "./laptop.png";
export { default as Suit } from "./suit.png";
export { default as Headset } from "./headset.png";
export { default as Sneakers } from "./sneekers1.png";
export { default as Sneakers2 } from "./sneekers2.png";
export { default as Sneakers3 } from "./sneekers3.png";
export { default as Airpodmax } from "./airpodmax.png";
export { default as Shoe } from "./shoe.png";
export { default as Sound } from "./sound.png";
export { default as Trouser } from "./trouser.png";
export { default as Wears } from "./wears.png";
export { default as SweatShirt } from "./sweatshirt.png";
export { default as Profile } from "./profile 1.png";
export { default as Profile2 } from "./profile 2.png";
export { default as Profile3 } from "./profile 3.png";
export { default as BlackMan } from "./black-businessman.png";
export { default as Ellipse } from "./Ellipse1.png";
export { default as AuthHero } from "./authhero.png";
